spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    mail:
      host: smtp.gmail.com
      port: 465
      protocol: smtps
      username: example@xxx.com
      password: xxx

    api:
      hostUrl: http://localhost:8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.session: INFO
    org.springframework.web.servlet: DEBUG
    org.hibernate: ERROR
